### ISSUE TITLE
Align title vertically when subtitle is nil

### ISSUE THREAD

**Issue by dtomicAZ** [donileo/RMessage#30]
Hi,

@donileo Could you please align title to be vertically centered when subtitle is not presented, thank you.

**Comment by dtomicAZ** [comment]
@donileo I found this issue:
https://github.com/donileo/RMessage/issues/27

I set develop branch:
pod 'RMessage', :git => 'https://github.com/donileo/RMessage.git', :branch => 'develop'

I am using swift and I can't set value, I tried like this:
RMessageView.appearance().titleSubtitleLabelsSizeToFit = true

but get this error:
Value of type 'RMessageView' has no member 'titleSubtitleLabelsSizeToFit'

Do you how can I set this in swift, thank you.

**Comment by isadon** [comment]
@dtomicAZ I just tried the same thing as you in a Swift project. Works for me. Make sure you add "import RMessage" at the top of your file. Also your podfile should have "use_frameworks!" at the top.

As for vertical alignment of the title when there is no subtitle: that already happens when you set the  titleSubtitleLabelsSizeToFit to true.

**Comment by dtomicAZ** [comment]
@donileo I cleaned project and it is now working.

Now it is centered vertically, but also it is centered horizontally.
Can it be only centered vertically ? (and keep horizontally alignment left)

**Comment by isadon** [comment]
Can you post a picture or what you want the message to look like? Thatll help me explain how it can be done.

**Comment by dtomicAZ** [comment]
Actually it is ok, looks like it's looking better when is both vertically and horizontally aligned.

Thank you for your help.
