### ISSUE TITLE
Margins when a navigation bar is hidden are smaller than before

### ISSUE THREAD

**Issue by tdksk** [donileo/RMessage#38]
I tried 2.2.0 and found that margins in a message view when a navigation bar is hidden and a sub title is empty are different from 2.1.5. I like the layout in 2.1.5 because it has enough margins. Is this supposed to be this layout in 2.2.0?

2.2.0 | 2.1.5
--- | ---
![simulator screen shot - iphone se - 2018-02-23 at 10 41 40](https://user-images.githubusercontent.com/2177378/36574096-56f194a8-1887-11e8-812a-1b1f6323f28b.png) | ![simulator screen shot - iphone se - 2018-02-23 at 10 40 48](https://user-images.githubusercontent.com/2177378/36574095-56ba4fc0-1887-11e8-8af6-47f9452121e9.png)
```objc
[RMessage showNotificationWithTitle:NSLocalizedString(@"Tell the user something", nil)
                           subtitle:nil
                               type:RMessageTypeNormal
                     customTypeName:nil
                           callback:nil];
```

**Comment by isadon** [comment]
Thanks! I will release 2.2.1 to fix this issue. Can you pull develop and tell me if that looks a lot better? I notice the bottom margin isn't exactly the same but that’s because there was a bug where when specifying nil for a subtitle the label for the subtitle would still be on the notification just hidden hence giving a margin of 15 in the bottom in Release 2.1.5 versus 10 which is correct now in 2.2.0.

**Comment by tdksk** [comment]
I tried develop branch and it looks good to me! I understood that the bottom margin in 2.2.0 is exactly correct. Thanks!

**Comment by isadon** [comment]
@tdksk I have pushed out the hotfix release: 2.2.1 to fix this issue. If you are using cocoapods feel free to do a pod update RMessage to get it.

**Comment by tdksk** [comment]
I got 2.2.1 via CocoaPods. Thank you for your quick action!
