### ISSUE TITLE
View controller peeks at the top

### ISSUE THREAD

**Issue by nightfall708** [donileo/RMessage#43]
Hi,

It seems that when (spring) animating the message from the top, you can see the view controller on which we are presenting peek at the top for a brief moment. Has this been addressed before? supposedly the solution is making the height of the message window slightly higher.

**Comment by isadon** [comment]
Can you post a gif or video of what you are describing?

**Comment by nightfall708** [comment]
Here: https://streamable.com/x5j02 
I've slow-mo'd it

**Comment by isadon** [comment]
Ok I see it. Yea, RMessage has done this ever since the animation was spring based which I think was since first release or very close to  first release. You could fork and essentially disable the spring animation or make the height longer to get the effect you are looking for but maybe the effect you want is not really what you want.

Functionality 2: With a bigger height and keeping the spring animation the animation would look like the height is shrinking from the bottom which I think would look weird.

Functionality 1: Disabling the spring animation is another option but it can’t currently be done without chamging the files  because its not a user changeable setting.

I’ll look into adding the ability to disabling the spring animation and making it normal.

**Comment by isadon** [comment]
Hi @gerbil802 on my previous post which of the two functionalities is it that you expect. I tried looking at the animation generated by disabling the spring animation but as expected I find it really may not be what you are looking for. Here is a gif:

Functionality 1:
![rmessage-no-spring](https://user-images.githubusercontent.com/1881038/38403208-bb3f57f6-392f-11e8-8787-8cbc3f42029d.gif)

Functionality 2:
![rmessage-spring2](https://user-images.githubusercontent.com/1881038/38403535-25ec7564-3932-11e8-89dd-c3617cf88398.gif)

Im expecting you probably want Functionality 2.

**Comment by isadon** [comment]
Hi, please test the latest develop branch. Commit ab9bc68c339e should fix this issue and behave like  Functionality 2 as above. Normally I wouldn't make these kind of changes the default for everyone but I "believe" functionality 2 universally looks better than animating with the gap. If enough users request the old functionality I'll look into restoring it via some flag.

**Comment by nightfall708** [comment]
@donileo Yep, Functionality 2 is exactly what I wanted! I don't think it looks like the height is shrinking because the text layout is aligned to the bottom.
