### ISSUE TITLE
Minimum deployment target

### ISSUE THREAD

**Issue by ucerxxx** [donileo/RMessage#7]
Hi! 

Is there any problems on iOS8? I checked on simulator - looks like everything is working.
So what was the reason for setting iOS9+ and is it possible to support iOS8, to use it with cocoapods?

**Comment by isadon** [comment]
Hi @ucerxxx, I understand I may have made that move with too much haste. I made the minimum target iOS 9, simply because thats the target I want to support moving forward. Am I wrong in thinking that the higher deployment target will give me side benefits such as bug fixes, improvements and possibly better performance that Apple has include in the higher target? Is the iOS 8 install base significantly big to warrant supporting that? When iOS10 and iOS11 comes out unless theres a major reason to up the target I don't plan on moving the target up at that time.

The other argument is that yes, RMessage does work fine with iOS7 and higher but does that mean that should be the supported target? Give me some feedback, and I'll do what is right. Maybe my first argument is incorrect and not really warranted. If thats the case I'll roll back the minimum deployment target.

As far as how to make it work, simply up your Cocoapods deployment target to 9.0. Unless there is a pod in your podfile that does not support support iOS9 it all should work fine.

**Comment by ucerxxx** [comment]
I think that if there is now troubles with running on lower versions - no reasons to neglect it. If you will encounter problems in future with newer iOS,  you can anytime set higher minimum deployment target. One more reason (imho) is that this is objective-c library, so it should target to older projects which can support older devices.

Anyway I would be grateful, because it will help at least me - I used TSMessages in one of my old projects (iOS8+) and going to update it. I would like to replace it with RMessage and do it properly, without adding to project directly

**Comment by isadon** [comment]
@ucerxxx Issue closing soon. RMessage 2.1.2 properly maintains support for iOS7 and higher, so make sure to upgrade to that. At the end of the day the main reason for keeping support for iOS7 at least for now is that it was incorrect of me to drop support for iOS7 yet not make this a major release ~ 3.x.x. Thanks and feel free to retest.
